### ISSUE TITLE
无法使用all

### ISSUE THREAD

**Issue by KunBuFenZi** [NishinomiyaAki/koishi-plugin-nezha-api#1]
2024-07-03 00:32:14 [W] command nezha.all
TypeError: Cannot read properties of null (reading '0')
at getCpuCoreNum (/koishi/node_modules/koishi-plugin-nezha-api/lib/index.js:314:40)
at Command.<anonymous> (/koishi/node_modules/koishi-plugin-nezha-api/lib/index.js:389:27)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Array.<anonymous> (/koishi/node_modules/[@koishijs](https://www.nodeseek.com/member?t=koishijs)/core/lib/index.cjs:1114:14)
at async Command.execute (/koishi/node_modules/[@koishijs](https://www.nodeseek.com/member?t=koishijs)/core/lib/index.cjs:1128:22)
at async /koishi/node_modules/[@koishijs](https://www.nodeseek.com/member?t=koishijs)/core/lib/index.cjs:2162:22
at async Proxy.withScope (/koishi/node_modules/[@koishijs](https://www.nodeseek.com/member?t=koishijs)/core/lib/index.cjs:2065:22)
at async next (/koishi/node_modules/[@koishijs](https://www.nodeseek.com/member?t=koishijs)/core/lib/index.cjs:853:16)
at async next (/koishi/node_modules/[@koishijs](https://www.nodeseek.com/member?t=koishijs)/core/lib/index.cjs:853:16)
at async Processor._handleMessage (/koishi/node_modules/[@koishijs](https://www.nodeseek.com/member?t=koishijs)/core/lib/index.cjs:864:22)

![ac1d0e03c825228047b7e6bf929453ec](https://github.com/NishinomiyaAki/koishi-plugin-nezha-api/assets/63092147/2811a6e7-7d60-446c-b293-ce441cd75ac1)

GPT:

这个错误提示表明在执行 nezha.all 命令时发生了问题，具体是在 nezha-plugin-nezha-api 模块中的 getCpuCoreNum 函数出现了错误。错误信息显示试图读取一个空对象的属性，导致了 Cannot read properties of null (reading '0') 错误。

可能的原因是在执行命令时，某些必要的数据结构或对象并未正确初始化或获取到。你可以检查相关代码，特别是 nezha-plugin-nezha-api 模块中涉及到的 getCpuCoreNum 函数，确认其在处理数据时的逻辑和错误处理是否完备。

**Comment by KunBuFenZi** [comment]
![0a858b3953fa1e9de91d85f491ced0e1](https://github.com/NishinomiyaAki/koishi-plugin-nezha-api/assets/63092147/a1e175bd-da85-4404-9f9a-a3e6448eecb4)
![24ad702c4f3bc5ddc41c08dedeadfd3d](https://github.com/NishinomiyaAki/koishi-plugin-nezha-api/assets/63092147/674fb497-ffd6-47cb-bcbb-25a7c8a5fea9)
除了all 都能用似乎

**Comment by KunBuFenZi** [comment]
![b8ca4fdc9ef8e73e2c7346aac9ba6e06](https://github.com/NishinomiyaAki/koishi-plugin-nezha-api/assets/63092147/71aadd0f-b5ed-4bec-b703-1bda5b491e41)
nezha官方bot正常

**Comment by NishinomiyaAki** [comment]
> 2024-07-03 00:32:14 [W] command nezha.all TypeError: Cannot read properties of null (reading '0') at getCpuCoreNum (/koishi/node_modules/koishi-plugin-nezha-api/lib/index.js:314:40) at Command. (/koishi/node_modules/koishi-plugin-nezha-api/lib/index.js:389:27) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async Array. (/koishi/node_modules/[@koishijs](https://www.nodeseek.com/member?t=koishijs)/core/lib/index.cjs:1114:14) at async Command.execute (/koishi/node_modules/[@koishijs](https://www.nodeseek.com/member?t=koishijs)/core/lib/index.cjs:1128:22) at async /koishi/node_modules/[@koishijs](https://www.nodeseek.com/member?t=koishijs)/core/lib/index.cjs:2162:22 at async Proxy.withScope (/koishi/node_modules/[@koishijs](https://www.nodeseek.com/member?t=koishijs)/core/lib/index.cjs:2065:22) at async next (/koishi/node_modules/[@koishijs](https://www.nodeseek.com/member?t=koishijs)/core/lib/index.cjs:853:16) at async next (/koishi/node_modules/[@koishijs](https://www.nodeseek.com/member?t=koishijs)/core/lib/index.cjs:853:16) at async Processor._handleMessage (/koishi/node_modules/[@koishijs](https://www.nodeseek.com/member?t=koishijs)/core/lib/index.cjs:864:22)
> 
> ![ac1d0e03c825228047b7e6bf929453ec](https://private-user-images.githubusercontent.com/63092147/345127841-2811a6e7-7d60-446c-b293-ce441cd75ac1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5Nzg3NzMsIm5iZiI6MTcxOTk3ODQ3MywicGF0aCI6Ii82MzA5MjE0Ny8zNDUxMjc4NDEtMjgxMWE2ZTctN2Q2MC00NDZjLWIyOTMtY2U0NDFjZDc1YWMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDAzNDc1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3YWJlZjcwNGU0MDBlYjI2YWU2NDJlNjNiZmJmYmZjN2Y5YWI4Zjk2NTFhNjQwM2UyMDcwMTk4NjAxZGJkZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0lcsZ4oI9c8kIVXJqSjAj9GErtVhhB5QVss5RTbJ5Ek)
> 
> GPT:
> 
> 这个错误提示表明在执行 nezha.all 命令时发生了问题，具体是在 nezha-plugin-nezha-api 模块中的 getCpuCoreNum 函数出现了错误。错误信息显示试图读取一个空对象的属性，导致了 Cannot read properties of null (reading '0') 错误。
> 
> 可能的原因是在执行命令时，某些必要的数据结构或对象并未正确初始化或获取到。你可以检查相关代码，特别是 nezha-plugin-nezha-api 模块中涉及到的 getCpuCoreNum 函数，确认其在处理数据时的逻辑和错误处理是否完备。

已提交修复，在koishi依赖管理更新本插件
